# Validate the goReleaser configuration

name: validate_goreleaser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate_goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.2
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 'v1.5.0'
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
